package in.ramakant.rpg.common.constants;

public interface PropertyKeyConstants {
    String MAX_BONUS_POINTS = "MAX_BONUS_POINTS";
    String FIGHT_FLEEING_HP_REDUCTION = "FIGHT_FLEEING_HP_REDUCTION";
    String LEVEL_UP_BONUS = "LEVEL_UP_BONUS";
    String FIGHT_DAMAGE_VARIATION_MULTIPLIER = "FIGHT_DAMAGE_VARIATION_MULTIPLIER";
    String EXP_TO_FIRST_LEVEL_UP = "EXP_TO_FIRST_LEVEL_UP";
    String NEXT_LEVEL_EXP_MULTIPLIER = "NEXT_LEVEL_EXP_MULTIPLIER";
    String BASE_HEALTH = "BASE_HEALTH";
    String BASE_DAMAGE = "BASE_DAMAGE";
    String BASE_DAMAGE_VARIATION = "BASE_DAMAGE_VARIATION";
    String NO_OF_ENEMIES="NO_OF_ENEMIES";
}
